//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubChallengeBeta.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int UserImageId { get; set; }
        public string UserId { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
